apiVersion: v1
kind: Service
metadata:
  name: dbsynch
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: dbsynch
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbsynch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbsynch
  template: 
    metadata:
      labels:
        app: dbsynch
    spec:
      containers:
      - name: dbsynch
        image: alex176/dbsynch-service:v1.3
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 250m
            memory: 64M
          limits:
            cpu: 1000m
            memory: 128M
