apiVersion: v1
kind: Service
metadata:
  name: flask-app-preprocessing
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-app-preprocessing
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-preprocessing
  template: 
    metadata:
      labels:
        app: flask-app-preprocessing
    spec:
      containers:
      - name: flask-app-preprocessing
        image: alex176/azure-data-preprocessing-service:v1.1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

