apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app-frontend
  template: 
    metadata:
      labels:
        app: nodejs-app-frontend
    spec:
      containers:
      - name: nodejs
        image: alex176/azure-scalable-app-prototype-frontend:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodejs-app-frontend
  type: LoadBalancer
