apiVersion: v1
kind: Service
metadata:
  name: mongodb-backup
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-backup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-backup
  template: 
    metadata:
      labels:
        app: mongodb-backup
    spec:
      containers:
      - name: mongodb-backup
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user
              key: db-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: db-password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

