apiVersion: v1
kind: Service
metadata:
  name: dbsynch
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: dbsynch
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbsynch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbsynch
  template: 
    metadata:
      labels:
        app: dbsynch
    spec:
      containers:
      - name: dbsynch
        image: alex176/azure-dbsynch-service:v1.0
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi