apiVersion: v1
kind: Service
metadata:
  name: app-preprocessing
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-app-preprocessing
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-preprocessing
  template: 
    metadata:
      labels:
        app: flask-app-preprocessing
    spec:
      containers:
      - name: data-preprocessing-app
        image: alex176/azure-data-preprocessing-service:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

