apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: inference
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template: 
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference-service
        image: alex176/inference-service:v1.1
        resources:
          requests:
            cpu: 1000m
            memory: 512M
          limits:
            cpu: 2000m
            memory: 1024M
