apiVersion: v1
kind: Service
metadata:
  name: mlmanager-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: mlmanager
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlmanager
  template: 
    metadata:
      labels:
        app: mlmanager
    spec:
      containers:
      - name: mlmanager-service
        image: alex176/mlmanager-service:v1.1
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 1000m
            memory: 512M
          limits:
            cpu: 2000m
            memory: 1024M
