apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-mongodb-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081       # Exposing 
      targetPort: 8081 # Targeting 
  selector:
    app: mongoexpress-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress-mongodb
  template: 
    metadata:
      labels:
        app: mongoexpress-mongodb
    spec:
      containers:
      - name: mongoexpress-mongodb
        image: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: db-user
              key: db-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: db-password
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://$(ME_CONFIG_MONGODB_ADMINUSERNAME):$(ME_CONFIG_MONGODB_ADMINPASSWORD)@mongodb:27017
        - name: ME_CONFIG_BASICAUTH
          value: "false"

        resources:
          requests:
            cpu: 100m
            memory: 64M
          limits:
            cpu: 500m
            memory: 128M
