"host": "localhost"
"port": 27017
"backup_host": "localhost"
"backup_port": 27018
"database": "fantanba"
"user": "mongodb-user"
"password": "m0ng0d8"
"games_stats_collection_name": "games_stats"
"teams_stats_collection_name": "teams_stats"
