"host": "mldatabase-service"
"port": 27017
"database": "mldatabase"
"user": "mongodb-user"
"password": "m0ng0d8"
"data_preprocessing_service_host": "flask-app-preprocessing"
"sleep_time": 2
"preprocessing-service-url": "http://flask-app-preprocessing:5000"